### PR TITLE
Update vscode-eslint to 2.2.6

### PR DESCRIPTION
**Pull request by alecmev**
Build using Webpack, so it's closer to upstream. Smoke-tested locally. I updated the build, but I know nothing about LSP, so I don't know if I need to touch anything else, and where to look for things to touch/add/remove. Please do jump in!

### CODE REVIEW

**Review by rchl — APPROVED** [review]
Looks good. Thanks!

Doesn't look like any new settings were introduced or changed between those versions so nothing more should be necessary.

**Comment by alecmev** [comment]
Please don't merge yet, I'm in the process of switching from `NpmClientHandler` to `GenericClientHandler`, since `node_modules` isn't needed anymore, and the caching neither.

**Comment by predragnikolic** [comment]
The switching to GenericClientHandler can be a separate PR.🙂

**Comment by alecmev** [comment]
That works too! :wink:

**Comment by rchl** [comment]
Actually the best is the third option - just set `skip_npm_install` class property on `NpmClientHandler` - https://sublimelsp.github.io/lsp_utils/client_handlers.html#lsp_utils.NpmClientHandler.skip_npm_install

**Comment by alecmev** [comment]
Thought about that, but it will still look for `package.json`, which isn't needed anymore, and create a new cache entry for each Node version, if I understand it right. I aim to have just `language-server.js` in the root of the project and nothing else.

**Comment by rchl** [comment]
There is a purpose in having `package.json` present. That way the ST package knows when to update the source files that are stored in package storage directory (as those are not used directly from the compressed package files). Otherwise the eslint server source files would not get updated on updating the package. Or alternatively would update on every package update, even when not needed.

**Comment by alecmev** [comment]
I might be misunderstanding how LSP works! From what I can see, the server "binary" is shipped with this plugin, and it has no dependencies (Webpack bundles it all up), and this plugin is tightly-coupled to the server, so there's no reason to do anything if a different Node version is used, as long as it's supported, and there are no other variables. Or is there more to it?

**Comment by rchl** [comment]
Yes, ST packages typically ship as zip files (with `.sublime-package` extension). The server files need to be copied outside of the package so that node process can access those.

**Comment by alecmev** [comment]
The reason I went down this path was to simplify server development, so I could `ln -s` the `out` directory into the project, but I'll just do that in the cache instead.

Thanks for the explanation!

**Pull request merged**
