### PR TITLE
Update eslint server to latest master

### PR DESCRIPTION
**Pull request by rchl**
## Todo
 - [x] Only release this for ST4 as it replaces formatting-on-save with code-actions-on-save so it's a breaking change.
 - [x] Only release once CAOS (https://github.com/sublimelsp/LSP/pull/1087) is released.
 - [x] Check if there are any changes in settings in the latest version and update default settings if needed
 - [x] Add a custom handler for the `workspace/configuration` request, using new API (based on the previous attempt at https://github.com/sublimelsp/LSP-eslint/blob/ec1157fad26af60e95b198b6f836388a35ae52f7/plugin.py#L224-L237)

### CODE REVIEW

**Comment by rwols** [comment]
That custom `workspace/configuration` cannot work, because looking up a handler is first done in the Session object. If it's not found there, only then do we look it up in AbstractPlugin.

But we can change the behavior of course.

**Comment by rchl** [comment]
We could potentially have a `workspace/configuration`-specific hook to be able to alter the returned configuration?

**Comment by rwols** [comment]
Yes I think that would be best. It's probably not a good idea to first lookup handlers in the plugin class (we've already been there with inheritance).

**Comment by rchl** [comment]
I can integrate and release it already. The `on_workspace_configuration` will not work until next release of LSP but it's fine as it's an optional bonus.

**Pull request merged**
